feat: add troubleshoot tutorial for JS SyntaxError: missing variable name (#296)
* feat: add troubleshoot tutorial for JS SyntaxError

SyntaxError: missing variable name

* Update how-to-troubleshoot-js-syntax-error-missing-variable-name.md

* Copyedit

Co-authored-by: ltagliaferri <lisa.tagliaferri@gmail.com>